### ISSUE TITLE
[WDS] Disconnected! console error like into the demo

### ISSUE THREAD

**Issue by vallica** [0xfe/vexchords#14]
Hello,

Thanks a lot for your work that I was able to set-up on a basic HTML test page.

But I encounter browser console errors about "WDS" (You will found the sames errors into the live demo at http://vexflow.com/vexchords/) : 

`[WDS] Disconnected!`
`GET http://localhost:8203/sockjs-node/info?t=1586419101157 net::ERR_CONNECTION_REFUSED`
`GET http://localhost:8203/sockjs-node/info?t=1586419107279 net::ERR_CONNECTION_REFUSED`
`GET http://localhost:8203/sockjs-node/info?t=1586419136864  net::ERR_CONNECTION_REFUSED`
`etc...`

Can you advice me a proper way to disable this connections attempts ?

Cheers,
Seb

**Comment by vallica** [comment]
Please I havn't found solution for this little problem which slows down the execution of the script and fills in red the console... thanks in advance !

**Comment by 0xfe** [comment]
This is weird. I'll take a look

**Comment by 0xfe** [comment]
Looks like this is happening because it's a development build (trying to connect to webpack-dev-server). If you use the production build, you shouldn't see these issues.  Use `npm run build` to create a production build.

**Comment by vallica** [comment]
Hi,

Thanks for your help ! Is there any production build in download ? Because I failed to setup an npm environment on my Mac to build it... sorry !
